delete DBeli
delete DJual
delete HBeli
delete HJual
delete HTerima
delete DTerima
delete DReturBeli
delete DReturJual
delete HReturBeli
delete HReturJual
delete TbBarang
delete TbKontakSupplier
delete TbSatuan
delete TbStaff
delete TbSupplier
delete TbPelanggan
delete TbPembayaran