insert into TbSupplier values('Unilever','Kupang Panjaan')
insert into TbSupplier values('Wings','Diponegoro')
insert into TbSupplier values('Alexa','GWalk')
insert into TbSupplier values('Msi','Putat Jaya')
insert into TbSupplier values('Asus','Ngagel Selatan')